Debug: true
LogLevel: debug

grpc:
  host: 0.0.0.0
  port: 8088

redis:
  host: 127.0.0.1
  port: 6379
  password:

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

mysql:
  host: 127.0.0.1
  port: 3306
  database: match
  username: root
  password: 123456

MeConf:
  accuracy: 8 #计算精度
