grpc:
  host: gome
  port: 8088

redis:
  host: redis
  port: 6379
  password: 123456

rabbitmq:
  host: rabbitmq
  port: 5672
  username: root
  password: 123456

mysql:
  host: 127.0.0.1
  port: 3306
  database: dbname
  username: root
  password: 123456

gomengine:
  accuracy: 8 #计算精度

